#
# used to patch issuers with dynamic service
# account secret name
#

kubectl:
  image:
    repository: dtr.dev.cray.com/loftsman/loftsman
    tag: latest
    pullPolicy: IfNotPresent

# Chart only deploys vault-backed issuers (e.g., no
# self-signed currently). All values shown are required.
# Each list member under vault-services must# be unique,
# minimally by vault-pki-role.
#
# See the vault-issuers.yaml template for a mapping to
# cert-manager issuer configuration.
#

vaultIssuers:
  Services:
      namespace: services
      vaultServer: "http://cray-vault.vault.svc.cluster.local:8200"
      vaultPKIRole: common
      vaultPKIPath: pki_common/sign
      vaultK8SAuthPath: /v1/auth/kubernetes
#  Fabric:
#      namespace: fabric-mgmt
#      vaultServer: "http://cray-vault.vault.svc.cluster.local:8200"
#      vaultPKIRole: fabric_mgmt
#      vaultPKIPath: pki_fabric_mgmt/sign
#      vaultK8SAuthPath: /v1/auth/kubernetes
