apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-jobs-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-jobs-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-jobs-role