{{- /*
Copyright 2020 Hewlett Packard Enterprise Development LP
*/ -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cray-precache-images.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cray-precache-images.name" . }}
    {{- include "cray-precache-images.common-labels" . | nindent 4 }}
  annotations:
    {{- include "cray-precache-images.common-annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cray-precache-images.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cray-precache-images.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- include "cray-precache-images.pod-annotations" . | nindent 8 }}
    spec:
      containers:
      - name: cache-images 
        image: {{ include "cray-precache-images.image-prefix" . }}{{ .Values.alpineImage }}
        command:
           - /bin/sh
           - -c
           - "while true; do echo $(date -u); /scripts/cache_images.sh; echo ''; sleep $(cat /scripts/cache_refresh_seconds); done"
        volumeMounts:
        - name: crictl
          mountPath: /usr/local/bin
        - name: cache-images-script
          mountPath: /scripts
        - name: containerd
          mountPath: /var/run
      volumes:
      - name: crictl
        hostPath:
          path: /usr/local/bin
      - name: cache-images-script
        configMap:
          name: cray-precache-images
          defaultMode: 0744
      - name: containerd
        hostPath:
          path: /var/run
