---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-cray-etcd-operator-pods
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: wait-for-cray-etcd-operator-pods
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      serviceAccountName: cray-etcd-operator-jobs
      containers:
        - name: wait
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          command:
            - '/bin/sh'
          args:
            - '-c'
            - '/usr/local/bin/wait-for-pods cray-etcd-operator-etcd-operator-etcd-backup-operator cray-etcd-operator-etcd-operator-etcd-operator cray-etcd-operator-etcd-operator-etcd-restore-operator'
