# RoleBinding for PSP in vault namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $op := index .Values "vault-operator" }}{{ $op.watchNamespace}}-psp
  namespace: {{ $op := index .Values "vault-operator" }}{{ $op.watchNamespace}} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:{{ $op := index .Values "vault-operator" }}{{ $op.watchNamespace}}
