# Default values for cray-externaldns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Settings for the TCP+UDP services which share a load balancer IP
sharedIPServices:
  customerAccess:
    # Additional annotations to e.g., set MetalLB address pool, external hostname
    annotations:
      metallb.universe.tf/address-pool: customer-access-static
      #external-dns.alpha.kubernetes.io/hostname:

     # Statically assign a specific IP
     #loadBalancerIP:

  hardwareManagement:
    # Additional annotations to e.g., set MetalLB address pool, external hostname
    annotations:
      metallb.universe.tf/address-pool: hardware-management
      #external-dns.alpha.kubernetes.io/hostname:

      # Statically assign a specific IP
      #loadBalancerIP:

kubectl:
  image:
    repository: dtr.dev.cray.com/loftsman/loftsman
    tag: latest
    pullPolicy: IfNotPresent

# coredns is a subchart for us
coredns:
  replicaCount: 2
  image:
    repository: coredns/coredns
    tag: "1.6.2"
    pullPolicy: Always

  # A post-install hook applies these annotations to the coredns deployment.
  podAnnotations:
    # Disable istio sidecar since etcd doesn't use it and external clients do
    # not require authentication.
    sidecar.istio.io/inject: "false"

  serviceType: "ClusterIP"

  prometheus:
    monitor: # This depends on ServiceMonitor from apiVersion: monitoring.coreos.com/v1
      enabled: false

  serviceAccount:
    create: true

  rbac:
    # If true, create & use RBAC resources
    create: true
    # If true, create and use PodSecurityPolicy
    pspEnable: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    # name:

  # isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
  isClusterService: false

  servers:
  - zones:
    - zone: .
      use_tcp: true
    port: 53
    plugins:
    - name: errors
    - name: health
    - name: log
    # Serves a /ready endpoint on :8181
    - name: ready
    - name: kubernetes
      parameters: cluster.local
    # Serves all load balancers in an internal.shasta zone
    - name: k8s_external
      parameters: internal.shasta
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: hosts
      parameters: /etc/coredns/hosts
      configBlock: |-
        fallthrough
    # Reads from etcd which is populated by external_dns
    - name: etcd
      parameters: vshasta.shasta.cray.com # How can we template this?
      configBlock: |-
        stubzones
        path /skydns
        endpoint http://cray-externaldns-etcd-client:2379

  # Use `zoneFiles` to populate hosts db as configured under `servers`. See
  # also https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/.
  zoneFiles:
  - filename: hosts
    contents: |
      # IP-address FQDN
      #10.1.2.3 ncn-w001.shasta.cray.com

external-dns:
  image:
    registry: docker.io
    repository: bitnami/external-dns
    tag: 0.5.16-debian-9-r8
  podAnnotations:
    # Disable istio sidecar since etcd doesn't use it.
    sidecar.istio.io/inject: "false"
  rbac:
    # If true, create & use RBAC resources
    create: true
    pspEnabled: true
  sources:
    - "service"
    - "istio-gateway"
    - "ingress"
  policy: sync
  istioIngressGateways:
    - "istio-system/istio-ingressgateway"
  provider: "coredns"
  coredns:
    etcdEndpoints: "http://cray-externaldns-etcd-client:2379"
  crd:
    create: true
  metrics:
    enabled: true
  resources:
    limits:
      cpu: "2"
      memory: 256Mi
    requests:
      memory: 50Mi
      cpu: 10m
  livenessProbe:
    initialDelaySeconds: 31
    periodSeconds: 30
    failureThreshold: 1
    successThreshold: 1
    timeoutSeconds: 20
  readinessProbe:
    initialDelaySeconds: 1
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 7

crayService:
  imagesHost: "dtr.dev.cray.com" # this value will always be set on helm install based on install context, this is a reasonable default
  etcdCluster:
    enabled: true
    size: 3
    version: "3.3.22"  #  NOTE: If you change this, ensure the version you are changing to is in the blob
    labels: {}
    annotations: {}
    pvc:
      enabled: true
      accessMode: "ReadWriteOnce"
      storage: 1Gi
