# Default values for cray-shared-kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

kafka:
  replicas: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: strimzi.io/name
                operator: In
                values:
                - cray-shared-kafka-kafka
            topologyKey: "kubernetes.io/hostname"
  resources:
    limits:
      cpu: "6"
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 64Mi

zookeeper:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: strimzi.io/name
                operator: In
                values:
                - cray-shared-kafka-zookeeper
            topologyKey: "kubernetes.io/hostname"
  resources:
    limits:
      cpu: "4"
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 64Mi
