#
# Copyright 2020 Hewlett Packard Enterprise Development LP
#
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-etcdbackup
  namespace: kube-system
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "{{ .Values.crayBaremetalEtcdBackup.crayEtcdBackupSchedule }}"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: kube-etcdbackup
            image: {{ include "cray-baremetal-etcd-backup.image-prefix" . }}{{ .Values.crayBaremetalEtcdBackup.kubeEtcdBackupImage }}
            envFrom:
            - configMapRef:
                name: kube-etcdbackup
            env:
              - name: S3_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: kube-etcdbackup-s3
                    key: S3_ACCESS_KEY
              - name: S3_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: kube-etcdbackup-s3
                    key: S3_SECRET_KEY
            volumeMounts:
            - name: etcd-client-certs
              mountPath: "/ssl"
              readOnly: true
          volumes:
          - name: etcd-client-certs
            secret:
              secretName: kube-etcdbackup-etcd
