{{- if .Values.init.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cray-nexus.fullname" . }}-init
  labels:
    nexus: setup
{{ include "cray-nexus.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "cray-nexus.fullname" . }}-init
      labels:
{{ include "cray-nexus.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: nexus-init
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: "{{ .Values.init.image.pullPolicy }}"
          env:
          - name: NEXUS_URL
            value: http://admin:admin123@nexus
          {{- if .Values.init.adminCredentials.enabled }}
          - name: NEXUS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.init.adminCredentials.metadata.name }}"
                key: password
          {{- end }}
          command:
          - /bin/bash
          - -c
          - |-
            set -x

            while ! nexus-ready; do
                echo >&2 "trying again in 10 seconds"
                sleep 10
            done

            set -e

            nexus-upload-script /usr/local/share/nexus-setup/groovy/*.groovy >&2
            nexus-enable-anonymous-access >&2
            nexus-remove-default-repos >&2
            nexus-enable-rut-auth >&2

            {{- if .Values.init.adminCredentials.enabled }}
            echo "$NEXUS_ADMIN_PASSWORD" | nexus-change-password admin >&2
            {{- end }}

{{- end }}
