
imagesHost: ""
image: openpolicyagent/opa
imageTag: 0.20.4-istio
imagePullPolicy: IfNotPresent

ingress:
  # namespace of the ingress containers
  # this will likely be different than the OPA namespace
  namespace: istio-system
  labelSelector:
    istio: ingressgateway

opa:
  replicas: 3
  port: 9191
  containerPort: 9191
  loglevel: info
  query: data.istio.authz.allow # this should never really change
  tls:
    enabled: false # TODO once we have cert manager
    secret: ""
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "2"
  # Timeout defaults to 200ms if not specified. Setting it to 10s, an
  # arbitrary long timeout, provides sufficient overhead to resolve
  # CASMPET-1804/2570 "deadline exceeded" gRPC errors for the ext_authz filter.
  # A newer version of OPA might fix this with better performance.
  timeout: 10s


# To overide the default policy in files/policy.rego follow the example below
# NOTE: If the policy changes or is overriden, you MUST do a rolling restart of the
# OPA pods to pick them up until we stop mounting as a configmap.

# policy: |
#   # Istio Ingress Gateway OPA Policy
#   package istio.authz

#   default allow = true

# Run each opa pod on a separate worker when possible
affinity:
  podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 1
       podAffinityTerm:
         labelSelector:
           matchExpressions:
           - key: app.kubernetes.io/name
             operator: In
             values:
             - cray-opa
         topologyKey: kubernetes.io/hostname
