# Required for the webhook certificate to match the 'cray' overlay service name
# Also updated in the cray-certmanager-init CRDs (*...webhookClientConfig.service instances)

# ExtraArgs (--enable-certificate-owner-ref=true) used to delete TLS key material (K8S secret)
# when certificate is deleted
# https://github.com/jetstack/cert-manager/pull/1828

kubectl:
  image:
    repository: dtr.dev.cray.com/loftsman/loftsman
    tag: 0.5.1

cert-manager:
   replicaCount: 3
   affinity:
      podAntiAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: app
                   operator: In
                   values:
                   - cert-manager
               topologyKey: kubernetes.io/hostname
   webhook:
      replicaCount: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - webhook
                topologyKey: kubernetes.io/hostname
      serviceName: cray-certmanager-cert-manager-webhook
   extraArgs:
      - "--enable-certificate-owner-ref=true"
   cainjector:
      replicaCount: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cainjector
                topologyKey: kubernetes.io/hostname
