nameOverride: ""
imagesHost: "registry.local"

global:
  chart:
    name: "" # set at deploy time automatically, no need to ever set explicitly
    version: "" # set at deploy time automatically, no need to ever set explicitly

trustDomain: shasta

server:
  replicaCount: 3
  fqdn: spire.local
  port: 8081
  logLevel: INFO
  jwtIssuer: http://spire.local/shasta/vshastaio
  caTTL: 24h
  svidDefaultTTL: 12h
  database: spire
  maxOpenDBConns: 20
  registrationPort: 54440
  tokenService:
    computeEntry: /compute/tenant1
    computeClusterEntry: /compute
    ncnEntry: /ncn/tenant1
    ncnClusterEntry: /ncn
    tokenTTL: 10800

  init:
    repository: spiffe-io/wait-for-it
    tag: latest
    pullPolicy: IfNotPresent

  init2:
    repository: baseos/alpine
    tag: 3.11.5
    pullPolicy: IfNotPresent

  image:
    repository: spiffe-io/spire-server
    tag: 0.12.0
    pullPolicy: IfNotPresent

  registration:
    repository: cray/cray-spire-tokens
    tag: 0.4.0
    pullPolicy: IfNotPresent

  persistentVolume:
    accessModes:
    - ReadWriteOnce
    size: 1Gi

cray-service:
  type: ""
  nameOverride: spire
  service:
    enabled: false
  sqlCluster:
    enabled: true
    instanceCount: 3
    postgresVersion: "11"
    volumeSize: 20Gi
    users:
      spire: []
    databases:
      spire: spire
    tls:
      issuer: cert-manager-issuer-common
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 2Gi

tls:
  issuer: cert-manager-issuer-common

agent:
  logLevel: INFO
  wlSocket: /run/spire/vshastaio/sockets

  init:
    repository: spiffe-io/wait-for-it
    tag: latest
    pullPolicy: IfNotPresent

  image:
    repository: spiffe-io/spire-agent
    tag: 0.12.0
    pullPolicy: IfNotPresent

jwks:
  domain: vshasta.io
  uriPrefix: spire-jwks-vshastaio
  logLevel: INFO
  port: 80
  replicaCount: 3

  image:
    repository: spiffe-io/oidc-discovery-provider
    tag: 0.12.0
    pullPolicy: IfNotPresent

  nginx:
    repository: cache/nginx
    tag: 1.18.0
    pullPolicy: IfNotPresent

bundle:
  uriPrefix: spire-bundle
  logLevel: INFO
  port: 8080
  replicaCount: 3

  image:
    repository: cray/cray-spire-bundle
    tag: 0.1.0-
    pullPolicy: IfNotPresent

bss:
  endpoint: http://cray-bss.services.svc.cluster.local/boot/v1/bootparameters
  curl:
    repository: curlimages/curl
    tag: 7.73.0

ncn:
  url: https://spire-tokens.spire:54440/api/token
  filename: join_token
  path: /root/spire/conf
  init:
    repository: baseos/alpine
    tag: 3.12.0
  curl:
    repository: curlimages/curl
    tag: 7.73.0
  pause:
    repository: k8s.gcr.io/pause
    tag: 3.2
