apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire.name" . }}-jwks-config
data:
  spire-jwks-provider.conf: |
    log_level = "{{ .Values.jwks.logLevel }}"
    log_requests = true
    domain = "{{ .Values.jwks.domain }}"
    listen_socket_path = "/run/spire/jwks/provider.sock"

    workload_api {
      socket_path = "/run/spire/sockets/agent.sock"
      trust_domain = "{{ .Values.trustDomain }}"
    }
  spire-jwks-sockethack: |
    #!/bin/sh
    while [ ! -S /run/spire/jwks/provider.sock ]; do sleep 1; done
    chmod 777 /run/spire/jwks/provider.sock
    exit 0
  spire-jwks-socketwait: |
    #!/bin/sh
    while [ ! -S /run/spire/sockets/agent.sock ]; do sleep 5; done
    exit 0
