apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spire.fullname" . }}-jwks
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-jwks
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jwks.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spire.name" . }}-jwks
  template:
    metadata:
    {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "spire.name" . }}-jwks
    spec:
      serviceAccountName: {{ include "spire.name" . }}-jwks
      affinity:
          podAntiAffinity:
             preferredDuringSchedulingIgnoredDuringExecution:
               - weight: 1
                 podAffinityTerm:
                   labelSelector:
                     matchExpressions:
                     - key: app
                       operator: In
                       values:
                       - {{ include "spire.name" . }}-server
                   topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init
        # Wait for the agent workload socket to appear
        image: "{{ include "spire.image-prefix" . }}{{ .Values.jwks.image.repository }}:{{ .Values.jwks.image.tag }}"
        imagePullPolicy: {{ .Values.jwks.image.pullPolicy }}
        command:
          - "/bin/sh"
          - "/run/spire/config/spire-jwks-socketwait"
        volumeMounts:
        - name: {{ include "spire.name" . }}-jwks-config
          mountPath: /run/spire/config
          readOnly: true
        - name:  {{ include "spire.name" . }}-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      containers:
      - name: {{ include "spire.name" . }}-jwks
        image: "{{ include "spire.image-prefix" . }}{{ .Values.jwks.image.repository }}:{{ .Values.jwks.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.jwks.image.pullPolicy }}
        args: ["-config", "/run/spire/config/spire-jwks-provider.conf"]
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "/run/spire/config/spire-jwks-sockethack"
        volumeMounts:
        - name: {{ include "spire.name" . }}-jwks-config
          mountPath: /run/spire/config
          readOnly: true
        - name:  {{ include "spire.name" . }}-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name:  {{ include "spire.name" . }}-socket
          mountPath: /run/spire/jwks
          readOnly: false
      - name: {{ include "spire.name" . }}-nginx
        image: "{{ include "spire.image-prefix" . }}{{ .Values.jwks.nginx.repository }}:{{ .Values.jwks.nginx.tag }}"
        imagePullPolicy: {{ .Values.jwks.nginx.pullPolicy }}
        command: ["nginx", "-c", "/run/spire/config/spire-jwks-nginx.conf"]
        env:
        - name: RESTART_CONFIG_VERSION
          value: "1"  # Change this when the config changes to cause a restart.
        volumeMounts:
        - name: {{ include "spire.name" . }}-nginx
          mountPath: /run/spire/config
          readOnly: true
        - name: {{ include "spire.name" . }}-socket
          mountPath: /run/spire/jwks
          readOnly: true
        ports:
        - containerPort: {{ .Values.jwks.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.jwks.port }}
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 3
      volumes:
      - name: {{ include "spire.name" . }}-jwks-config
        configMap:
          name: {{ include "spire.name" . }}-jwks-config
      - name: {{ include "spire.name" . }}-nginx
        configMap:
          name: {{ include "spire.name" . }}-nginx
      - name:  {{ include "spire.name" . }}-agent-socket
        hostPath:
          path: {{ .Values.agent.wlSocket }}
          type: Directory
      - name: {{ include "spire.name" . }}-socket
        emptyDir: {}
