apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire.name" . }}-nginx
data:
  spire-jwks-nginx.conf: |-
    daemon off;
    events {}
    http {
      access_log /dev/stdout;
      upstream jwks {
        server unix:/run/spire/jwks/provider.sock;
      }
      server {
        location / {
          proxy_hide_header 'Cache-Control';
          add_header 'Cache-Control' "public, max-age=300, must-revalidate, no-transform";
          proxy_pass http://jwks;
        }
      }
    }
