apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "spire.fullname" . }}-agent
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-agent
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "spire.name" . }}-agent
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      {{- with .Values.agent.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "spire.name" . }}-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ template "spire.name" . }}-agent
      initContainers:
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: "{{ include "spire.image-prefix" . }}{{ .Values.agent.init.repository }}:{{ .Values.agent.init.tag }}"
          imagePullPolicy: {{ .Values.agent.init.pullPolicy }}
          args: ["-t", "30", "spire-server:{{ .Values.server.port }}"]
      containers:
        - name: {{ template "spire.name" . }}
          image: "{{ include "spire.image-prefix" . }}{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args: ["-config", "/run/spire/config/spire-agent.conf"]
          volumeMounts:
            - name: {{ template "spire.name" . }}-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: {{ template "spire.name" . }}-socket
              mountPath: /run/spire/sockets
              readOnly: false
          livenessProbe:
            exec:
              command: ["/opt/spire/bin/spire-agent", "healthcheck", "-socketPath", "/run/spire/sockets/agent.sock"]
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
      volumes:
        - name: {{ template "spire.name" . }}-config
          configMap:
            name: {{ template "spire.name" . }}-agent-config
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: {{ template "spire.name" . }}-socket
          hostPath:
            path: {{ .Values.agent.wlSocket }}
            type: DirectoryOrCreate
