apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spire.fullname" . }}-update-bss
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-update-bss
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "spire.name" . }}-update-bss
    spec:
      containers:
        - name: {{ template "spire.name" . }}-update-bss
          image: "{{ include "spire.image-prefix" . }}{{ .Values.bss.curl.repository }}:{{ .Values.bss.curl.tag }}"
          command:
            - '/bin/sh'
          args:
            - '-x'
            - '-c'
            - 'curl -v --request PATCH -H "Content-Type: application/json" -d @/conf/bss-update.json "$ENDPOINT"'
          env:
            - name: ENDPOINT
              value: "{{ .Values.bss.endpoint }}"
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: conf
          configMap:
            name: spire-bss-config
