{{- if and .Values.servicesGateway.tls }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-gateway-cert
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    kind: Issuer
    name: cert-manager-issuer-common
  commonName: "{{ .Values.certificate.commonName }}"
  duration: 8760h
  renewBefore: 480h
  dnsNames:
{{- range .Values.certificate.dnsNames }}
     - "{{ . }}"
{{- end }}
{{- end }}