---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benji-db-claim
  namespace: backups
spec:
  storageClassName: ceph-cephfs-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
