---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tuple . "" | include "benji.fullname" }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
