#!/usr/bin/env python3

import boto3
import os
from argparse import ArgumentParser

os.environ["AWS_SHARED_CREDENTIALS_FILE"] = '/conf/credentials'
backup_bucket = 'etcd-backup'
s3_endpoint = open('/conf/s3_endpoint').read().replace('\n', '')

def main():
    parser = ArgumentParser(description='Lists backups for a given project')
    parser.add_argument('project')
    args = parser.parse_args()
    s3 = boto3.client('s3', endpoint_url=s3_endpoint)

    response = s3.list_objects_v2(Bucket=backup_bucket)
    for item in response['Contents']:
        if args.project in item['Key']:
            print(item['Key'])

if __name__ == '__main__':
    main()
