#!/bin/sh
# Copyright 2020, Cray Inc. All Rights Reserved.

project=$1
backup_name=$2
s3_endpoint=$(cat /conf/s3_endpoint)

if test "$#" -ne 2; then
    echo "Usage: restore_from_backup <project_name> <backup_name>"
    exit 1
fi

random_num=$RANDOM
file=/tmp/$project-restore-$random_num.yaml
line=$(grep $project /usr/local/sbin/clusters.txt)
namespace=$(echo $line | awk 'BEGIN { FS = "." } ; {print $2}')

cat > $file <<EOF
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdRestore"
metadata:
  name: $project-etcd
  namespace: $namespace
spec:
  etcdCluster:
    name: $project-etcd
    namespace: $namespace
  backupStorageType: S3
  s3:
    path: etcd-backup/$project/$backup_name
    awsSecret: etcd-backup-restore-aws-config
    forcePathStyle: true
    endpoint: $s3_endpoint
EOF

kubectl -n $namespace apply -f $file
