nameOverride: ""
imagesHost: "sms.local:5000"

chart:
  name: "" # set at deploy time automatically, no need to ever set explicitly
  version: "" # set at deploy time automatically, no need to ever set explicitly

replicas: 3
auditInterval: 60
constraintViolationsLimit: 20
auditFromCache: false
disableValidatingWebhook: false
auditChunkSize: 0
logLevel: INFO
emitAdmissionEvents: false
emitAuditEvents: false
image:
  repository: openpolicyagent/gatekeeper
  release: v3.1.1
  pullPolicy: IfNotPresent
nodeSelector: { kubernetes.io/os: linux }
affinity: {}
tolerations: []
podAnnotations:
  { container.seccomp.security.alpha.kubernetes.io/manager: runtime/default }
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

kubectl:
  image:
    repository: dtr.dev.cray.com/loftsman/loftsman
    tag: 0.5.1
