---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-etcd-periodic-backup-cron
  namespace: operators
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "{{ .Values.crayEtcdBackup.periodicCronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: "etcd-backup-restore"
          containers:
          - name: kube-etcd-periodic-backup-cron
            image: "{{ .Values.crayEtcdBackup.imageRegistry }}/loftsman/docker-kubectl:{{ .Values.crayEtcdBackup.kubectlImageVersion }}"
            command:
              - /bin/sh
              - -c
              - create_periodic_backups.sh
            volumeMounts:
              - name: etcd-backup-restore-config
                mountPath: /usr/local/sbin
          volumes:
            - name: etcd-backup-restore-config
              configMap:
                name: etcd-backup-restore-config
                defaultMode: 0755
