{{- $service := .Values.keycloak.keycloak.service -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  helm.sh/chart: {{ include "keycloak.chart" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - match:
        - uri:
            prefix: /{{ .Values.keycloak.keycloak.basepath }}
      route:
        - destination:
            host: {{ .Release.Name }}-http
            port:
              number: {{ $service.port }}
