---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-defrag
subjects:
  - kind: ServiceAccount
    name: etcd-defrag
    namespace: {{ .Values.crayEtcdDefrag.namespace }}
roleRef:
  kind: ClusterRole
  name: etcd-defragger
  apiGroup: rbac.authorization.k8s.io
