---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-etcd-defrag
  namespace: {{ .Values.crayEtcdDefrag.namespace }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: {{ .Values.crayEtcdDefrag.defragCronSchedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: "etcd-defrag"
          containers:
          - name: kube-etcd-defrag
            image: "{{ .Values.crayEtcdDefrag.imageRegistry }}/loftsman/docker-kubectl:{{ .Values.crayEtcdDefrag.imageVersion }}"
            command:
              - /bin/sh
              - -c
              - "/scripts/etcd_defrag.sh --defrag all --skip cray-hbtd-etcd"
            volumeMounts:
            - name: etcd-defrag
              mountPath: /scripts
          volumes:
          - name: etcd-defrag
            configMap:
              name: etcd-defrag
              defaultMode: 0744
