---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "cray-s3.fullname" . }}
  labels: {{ include "cray-s3.labels" . | nindent 4 }}
spec:
  host: {{ include "cray-s3.fullname" . }}
  trafficPolicy:
    tls:
      mode: DISABLE
