---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "cray-s3.fullname" . }}
  labels: {{ include "cray-s3.labels" . | nindent 4 }}
subsets:
- addresses: {{ range .Values.rgw.ips }}
  - ip: {{ . }}
  {{- end }}
  ports:
  - name: http-{{ include "cray-s3.fullname" . }}
    port: {{ .Values.rgw.port }}
    protocol: TCP
