---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-s3.fullname" . }}
  labels: {{ include "cray-s3.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-{{ include "cray-s3.fullname" . }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.rgw.port }}
