---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: operators
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"

---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: services
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "10m"
      memory: "64Mi"
    default:
      cpu: "2"
      memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: user
  name: user
