apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spire-intermediate.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "spire-intermediate.name" . }}
    {{- include "spire-intermediate.common-labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "spire-intermediate.fullname" . }}
      containers:
      - name: {{ include "spire-intermediate.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cray-vault-unseal-keys
                key: vault-root
          - name: PKI_PATH
            value: "{{ .Values.vaultPKIPath }}"
          - name: NAMESPACES
            value: "{{ .Values.namespaces }}"
