#
# Copyright 2020 Hewlett Packard Enterprise Development LP
#
global:
  authGateway: services/services-gateway

image:
  repository: quay.io/sighup/gatekeeper-policy-manager
  tag: v0.4.0

gatekeeper-policy-manager:
  ingress:
    enabled: true
  # Configure external hostname for Istio ingress
  externalAuthority: oa-gpm.local
  externalUrl: https://opa-gpm.local
