apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire.fullname" . }}-bundle
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-server
    {{- include "spire.common-labels" . | nindent 4 }}
