{{- $root := . -}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ include "spire.fullname" $root }}-tokens-tls"
spec:
  secretName: "{{ include "spire.fullname" $root }}-tokens-tls"
  duration: 7200h
  renewBefore: 24h
  commonName: "{{ include "spire.fullname" $root }}-tokens.{{ .Release.Namespace }}.cluster.svc"
  isCA: false
  keySize: 4096
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
  dnsNames:
    - "{{ include "spire.fullname" $root }}-tokens.{{ .Release.Namespace }}.cluster.svc"
    - "{{ include "spire.fullname" $root }}-tokens.{{ .Release.Namespace }}"
    - "{{ include "spire.fullname" $root }}-tokens"
  issuerRef:
    name: "{{ .Values.tls.issuer }}"
    kind: Issuer
