kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}
    {{- include "spire.common-labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
