apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "spire.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  host: {{ include "spire.fullname" . }}-server
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "spire.fullname" . }}-tokens
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  host: {{ include "spire.fullname" . }}-tokens
  trafficPolicy:
    tls:
      mode: DISABLE
