apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "spire.fullname" . }}-bundle
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-bundle
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "spire.name" . }}-bundle
  template:
    metadata:
      annotations:
      {{- with .Values.bundle.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "spire.name" . }}-bundle
    spec:
      serviceAccountName: {{ include "spire.name" . }}-bundle
      containers:
        - name: {{ template "spire.name" . }}-bundle
          image: "{{ include "spire.image-prefix" . }}{{ .Values.bundle.image.repository }}:{{ .Values.bundle.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bundle.image.pullPolicy }}
          args: ["-config", "/run/spire/config/spire-bundle.conf"]
          env:
            - name: DOMAIN
              value: "{{ .Values.trustDomain }}"
            - name: SERVER
              value: "{{ .Values.server.fqdn }}"
            - name: BUNDLE
              value: "/run/spire/bundle/bundle.crt"
          ports:
          - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          volumeMounts:
            - name: spire-bundle
              mountPath: /run/spire/bundle
              readOnly: true
      volumes:
        - name: spire-bundle
          configMap:
            name: spire-bundle
