apiVersion: v1
kind: Service
metadata:
  name: {{ template "percona-xtradb-cluster.fullname" . }}
  labels:
    app: {{ template "percona-xtradb-cluster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  {{- if .Values.proxy.enabled }}
  - name: proxyadm
    port: 6032
    protocol: TCP
    targetPort: 6032
  selector:
    app: {{ template "percona-xtradb-cluster.fullname" . }}-proxy
  {{- else }}
  selector:
    app: {{ template "percona-xtradb-cluster.fullname" . }}
  {{- end }}
    release: "{{ .Release.Name }}"
