# Copyright 2020, Cray Inc.
---
apiVersion: v1
name: cray-nexus
version: 0.6.0
description: Sonatype Nexus is an open source repository manager
appVersion: 3.25.0
home: "spet/cray-charts"
sources:
  - https://github.com/sonatype/nexus-public
  - https://github.com/travelaudience/docker-nexus
  - https://github.com/travelaudience/kubernetes-nexus
  - https://github.com/travelaudience/docker-nexus-backup
