---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cray-uas.name" . }}-mgr-configmap
data:
  cray-uas-mgr.yaml: |
    #
    # Copyright 2018, Cray Inc.  All Rights Reserved.
    #
    # Cray User Access Instance Manager Configuration file.
    #
    # This file provides the configuration data for the user access instance
    # manager.
    #
    ---
    uas_ips:   
{{ toYaml .Values.configs.mgr.uasIps | indent 6 }}
    volume_mounts:
{{ toYaml .Values.configs.mgr.volumeMounts | indent 6 }}
    uas_images:
{{ toYaml .Values.configs.mgr.uasImages | indent 6 }}
