---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cray-uas.name" . }}-mgr
subjects:
  - kind: ServiceAccount
    name: {{ include "cray-uas.name" . }}-mgr
    namespace: default
roleRef:
  kind: Role
  name: {{ include "cray-uas.name" . }}-mgr
  apiGroup: rbac.authorization.k8s.io