---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-node-labels
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, patch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-node-labels
subjects:
  - kind: ServiceAccount
    name: cray-node-labels
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cray-node-labels
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cray-node-labels
  namespace: {{ .Values.namespace }}
