---
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
version: "{{ .Values.crayService.etcdCluster.version }}"
metadata:
  name: "{{ include "cray-externaldns.fullname" . }}-etcd"
  labels:
    app.kubernetes.io/name: {{ include "cray-externaldns.fullname" . }}-etcd
    {{- with .Values.crayService.etcdCluster.labels -}}
    {{ toYaml . | nindent 4 -}}
    {{- end }}
  annotations:
    etcd.database.coreos.com/scope: clusterwide
    {{- with .Values.crayService.etcdCluster.annotations -}}
    {{ toYaml . | nindent 4 -}}
    {{- end }}
spec:
  size: {{ .Values.crayService.etcdCluster.size }}
  version: {{ .Values.crayService.etcdCluster.version }}
  repository: "{{ include "cray-service.image-prefix" . }}coreos/etcd"
  pod:
    busyboxImage: "{{ include "cray-service.image-prefix" . }}library/busybox:1.28.0-glibc"
    etcdEnv:
    - name: ETCD_AUTO_COMPACTION_RETENTION
      value: "1"
    - name: ETCD_SNAPSHOT_COUNT
      value: "10000"
    - name: ETCD_HEARTBEAT_INTERVAL
      value: "4200"
    - name: ETCD_ELECTION_TIMEOUT
      value: "21000"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: etcd_cluster
              operator: In
              values: ["{{ include "cray-externaldns.fullname" . }}-etcd"]
          topologyKey: kubernetes.io/hostname
    annotations:
      sidecar.istio.io/inject: "false"
    {{- if .Values.crayService.etcdCluster.pvc.enabled }}
    persistentVolumeClaimSpec:
      {{- if .Values.storageClass }}
      storageClass: {{ .Values.storageClass }}
      {{- end }}
      accessModes:
      - {{ .Values.crayService.etcdCluster.pvc.accessMode }}
      resources:
        requests:
          storage: {{ .Values.crayService.etcdCluster.pvc.storage }}
    {{- end }}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "{{ include "cray-externaldns.fullname" . }}-etcd-client-rule"
  labels:
    app.kubernetes.io/name: {{ include "cray-externaldns.fullname" . }}-etcd
spec:
  host: "{{ include "cray-externaldns.fullname" . }}-etcd-client"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "{{ include "cray-externaldns.fullname" . }}-etcd-rule"
  labels:
    app.kubernetes.io/name: {{ include "cray-externaldns.fullname" . }}-etcd
spec:
  host: "{{ include "cray-externaldns.fullname" . }}-etcd"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "cray-externaldns.fullname" . }}-wait-for-etcd-{{ .Release.Revision }}"
  labels:
    app.kubernetes.io/name: "{{ include "cray-externaldns.fullname" . }}-wait-for-etcd"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - name: "etcd-watcher"
          image: "{{ include "cray-service.image-prefix" . }}coreos/etcd:v3.3.22"
          command:
          - /bin/sh
          - -c
          - until etcdctl --endpoints http://$ETCD_HOST:$ETCD_PORT cluster-health; do echo "Waiting for etcd cluster"; sleep 2; done; echo 'ETCD READY';
          env:
            - name: ETCD_HOST
              value: "{{ include "cray-externaldns.fullname" . }}-etcd-client"
            - name: ETCD_PORT
              value: "2379"

