---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cray-externaldns.fullname" . }}-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cray-externaldns.fullname" . }}-jobs-cluster-role
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cray-externaldns.fullname" . }}-jobs-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ template "cray-externaldns.fullname" . }}-jobs
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cray-externaldns.fullname" . }}-jobs-cluster-role
