---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-{{ template "cray-certmanager-init.fullname" . }}-crds
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: wait-for-{{ template "cray-certmanager-init.fullname" . }}-crds
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      serviceAccountName: cray-{{ template "cray-certmanager-init.fullname" . }}-jobs
      containers:
        - name: wait
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'while [[ "$(kubectl get crds | grep cert-manager.io | wc -l)" != "6" ]]; do sleep 5; done'
