dependencies:
  - name: postgresql
    version: 7.7.2
    repository: "@stable"
    condition: postgresql.enabled
  - name: prometheus-pushgateway
    alias: pushgateway
    version: 1.2.6
    repository: "@stable"
