{{- $profile := index .Values "constraints" "selinux" "profile" -}}
{{- if index .Values "constraints" "selinux" "variables" $profile "enabled" -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPSELinuxV2
metadata:
  name: psp-selinux-v2
spec:
  enforcementAction: {{ index .Values "constraints" "selinux" "variables" $profile "enforcementAction" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- if index .Values "excludedNamespaces"}}
    excludedNamespaces:
    {{- range index .Values "excludedNamespaces"}}
    - {{ . }}
    {{- end }}
    {{- end }}
    # namespaces:
    #   - "production"  parameters:
  parameters:
    {{- if index .Values "constraints" "selinux" "variables" $profile "rule"}}
    rule: "{{ index .Values "constraints" "selinux" "variables" $profile "rule" }}"
    {{- end}}
    {{- if index .Values "constraints" "selinux" "variables" $profile "allowedSELinuxOptions"}}
    allowedSELinuxOptions:
    {{- range index .Values "constraints" "selinux" "variables" $profile "allowedSELinuxOptions"}}
      - level: {{ .level }}
        role: {{ .role }}
        type: {{ .type }}
        user: {{ .user }}
    {{- end }}
    {{ end}}
{{- end -}}
