{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ include "cray-vault.name" . }}"
  labels:
    app.kubernetes.io/name: {{ include "cray-vault.name" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.ingress.labels -}}
    {{- toYaml . | nindent 4 }}
    {{- end -}}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.ingress.gateway }}
  http:
    - match:
        - uri:
            prefix: "{{ .Values.ingress.prefix }}"
      rewrite:
        uri: "{{ .Values.ingress.uri }}"
      route:
        - destination:
            host: "{{ include "cray-vault.name" . }}"
            port:
              number: 8200
{{- end }}
