# Allow vault access to bind for k8s auth delegation
# required for clients to use K8S service account auth
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccountName }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccountName }}-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccountName }}-secrets
roleRef:
  kind: Role
  name: {{ .Values.serviceAccountName }}-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccountName }}-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
---
# Job support
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cray-vault-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cray-vault-jobs-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-vault-jobs-role-binding
subjects:
- kind: ServiceAccount
  name: cray-vault-jobs
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cray-vault-jobs-role