apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "{{ include "cray-vault.name" . }}"
spec:
  size: {{ .Values.vault.size }}
  image: "{{ include "cray-vault.image-prefix" . }}{{ .Values.vault.image }}"
  bankVaultsImage: "{{ include "cray-vault.image-prefix" . }}{{ .Values.vault.bankVaultsImage }}"
  statsdImage: "{{ include "cray-vault.image-prefix" . }}{{ .Values.vault.statsdImage }}"

  {{- if .Values.vault.antiaffinity.enabled }}
  podAntiAffinity: {{ .Values.vault.antiaffinity.topologyKey }}
  {{- end }}

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: {{ .Values.serviceAccountName }}

  # If resources for etcd are not set, the vault-operator will apply
  # defaults that have proven too low for our use.
  # See --
  # https://github.com/banzaicloud/bank-vaults/blob/chart/vault/1.1.0/operator/pkg/controller/vault/vault_controller.go#2043
  # https://github.com/banzaicloud/bank-vaults/blob/fe2edfa64f99b77a1b7719900ca8add5fa869d68/operator/deploy/cr-resource.yaml#L10

  resources:
    vault:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 768Mi
    etcd:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi

  # Specify how many nodes you would like to have in your etcd cluster
  # NOTE: -1 disables automatic etcd provisioning

  etcdSize: {{ .Values.etcd.clusterSize }}

  etcdPVCSpec:
    {{- if .Values.etcd.pvc.storageClass }}
    storageClass: {{ .Values.etcd.pvc.storageClass }}
    {{- end }}
    accessModes:
    - {{ .Values.etcd.pvc.accessMode }}
    resources:
      requests:
        storage: {{ .Values.etcd.pvc.storage }}

  etcdVersion: "{{ .Values.etcd.version }}"

  etcdAnnotations:
    etcd.database.coreos.com/scope: clusterwide

  etcdPodAnnotations:
    sidecar.istio.io/inject: "false"

  etcdRepository: "{{ include "cray-vault.image-prefix" . }}{{ .Values.etcd.image }}"
  etcdPodBusyBoxImage: "{{ include "cray-vault.image-prefix" . }}{{ .Values.etcd.busyboxImage }}"

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    kubernetes:
      secretNamespace: {{ .Release.Namespace }}

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      etcd:
        address: https://{{ include "cray-vault.etcdName" . }}:2379
        ha_enabled: "true"
        etcd_api: "v3"
    listener:
      tcp:
        tls_disable: true
        address: "0.0.0.0:8200"
    api_addr: http://{{ include "cray-vault.name" . }}.{{ .Release.Namespace }}:8200
    ui: {{ .Values.vault.ui }}

  # See: https://github.com/banzaicloud/bank-vaults/blob/master/vault-config.yml for more details.
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      # This rule is used by the cert-manager-issuer to sign certs for the services namespace
      - name: common
        rules: path "pki_common/sign/*" {
                  capabilities = ["update"]
               }

    auth:
      - type: kubernetes
        roles:
          # This role is used by the cert-manager-issuer to sign certs for the services namespace
          - name: common
            bound_service_account_names: ["cert-manager-issuer-common"]
            bound_service_account_namespaces: ["services"]
            policies: ["common"]
            ttl: 1h
          {{- range .Values.allowedAuthNamespaces }}
          - name: {{ .namespace | quote }}
            bound_service_account_names: {{ .serviceaccount | quote }}
            bound_service_account_namespaces: {{ .namespace | quote }}
            policies: allow_secrets
            ttl: {{ .ttl }}
          {{- end }}
      {{- if .Values.jwt.enabled }}
      - type: jwt
        path: jwt
        config:
          {{- range $key, $val := .Values.jwt.config }}
          {{ $key }}: {{ $val | quote }}
          {{- end }}
        roles:
          - name: default
            role_type: jwt
            bound_audiences:
              - {{ .Values.jwt.audience }}
            user_claim: preferred_username
            policies: allow_secrets
            ttl: {{ .Values.jwt.ttl | default "10m" }}
      {{- end }}

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 1
      # This configures the PKI vault used by cert-manager
      - path: pki_common
        type: pki
        description: Vault PKI Backend
        config:
          # This is for a year and a half and needs to be larger than any of the max_ttls below
          # This is used by the intermediate cert
          default_lease_ttl: 13140h
          # vault uses max_lease_ttl as the ttl for the generated CA
          max_lease_ttl: 87600h
        configuration:
          config:
            - name: urls
              issuing_certificates: http://{{ include "cray-vault.name" . }}.{{ .Release.Namespace }}:8200/v12/pki/ca
              crl_distribution_points: http://{{ include "cray-vault.name" . }}.{{ .Release.Namespace }}:8200/v12/pki/crl
          roles:
            - name: common
              max_ttl: 8760h
              allow_any_name: true
          {{- if eq .Values.pki.customCertificate.enabled false }}
          root/generate:
            - name: internal
              common_name: Shasta Internal CA
          {{- end }}

    {{- if .Values.pki.customCertificate.enabled }}
    startupSecrets:
      - type: pki
        path: pki_common/config/ca
        data:
         secretKeyRef:
          - name: {{ .Values.pki.customCertificate.secret }}
            key: ca.crt
          - name: {{ .Values.pki.customCertificate.secret }}
            key: ca.key
    {{- end }}
