# Note that this will trigger and fail the first scheduled backup while vault is deploying
# See: https://github.com/vmware-tanzu/velero/issues/1980

# https://velero.io/docs/v1.5/api-types/schedule/
apiVersion: velero.io/v1
# Standard Kubernetes Kind declaration. Required.
kind: Schedule
# Standard Kubernetes metadata. Required.
metadata:
  # Schedule name. May be any valid Kubernetes object name. Required.
  name: vault-daily-backup
  # Schedule namespace. Must be the namespace of the Velero server. Required.
  namespace: velero
# Parameters about the scheduled backup. Required.
spec:
  # Schedule is a Cron expression defining when to run the Backup
  schedule: 0 2 * * *
  # Template is the spec that should be used for each backup triggered by this schedule.
  template: # https://banzaicloud.com/docs/bank-vaults/backup/
    # Array of namespaces to include in the backup. If unspecified, all namespaces are included.
    # Optional.
    includedNamespaces:
    - vault
    # Array of resources to include in the backup. Resources may be shortcuts (e.g. 'po' for 'pods')
    # or fully-qualified. If unspecified, all resources are included. Optional.
    includedResources:
    - pv
    - pvc
    - secret
    - sealedsecret # not currently labeled below
    - vault
    - configmap
    - deployment
    - service
    - statefulset
    - pod
    - ingress
    - replicaset
    # Whether or not to include cluster-scoped resources. Valid values are true, false, and
    # null/unset. If true, all cluster-scoped resources are included (subject to included/excluded
    # resources and the label selector). If false, no cluster-scoped resources are included. If unset,
    # all cluster-scoped resources are included if and only if all namespaces are included and there are
    # no excluded namespaces. Otherwise, if there is at least one namespace specified in either
    # includedNamespaces or excludedNamespaces, then the only cluster-scoped resources that are backed
    # up are those associated with namespace-scoped resources included in the backup. For example, if a
    # PersistentVolumeClaim is included in the backup, its associated PersistentVolume (which is
    # cluster-scoped) would also be backed up.
    includeClusterResources: true
    labelSelector:
      matchLabels:
        vault_cr: cray-vault
    # Where to store the tarball and logs.
    storageLocation: default