apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: cray-istio
spec:
  profile: minimal
  hub: {{ .Values.hub }}
  tag: {{ .Values.tag }}
  components:
    pilot:
      enabled: true
      hub: {{ .Values.pilot.hub }}
      tag: {{ .Values.pilot.tag }}
  addonComponents:
    prometheus:
{{ toYaml .Values.addonComponents.prometheus | indent 6 }}
    kiali:
      enabled: true
    tracing:
      enabled: true
    grafana:
      enabled: true
  values:
    kiali:
{{ toYaml .Values.istio.kiali | indent 6 }}
    prometheus:
{{ toYaml .Values.istio.prometheus | indent 6 }}
    grafana:
{{ toYaml .Values.istio.grafana | indent 6 }}
