
hub: dtr.dev.cray.com/cray
tag: 1.6.13-cray1-20210202183713_549528c5da

kubectl:
  image:
    repository: dtr.dev.cray.com/loftsman/loftsman
    tag: 0.5.1

pilot:
  hub: dtr.dev.cray.com/cray
  tag: 1.6.13-cray1-20210202183713_549528c5da

meshConfig:
  accessLogFile: /dev/stdout

addonComponents:
  prometheus:
    enabled: true
    k8s:
      replicaCount: 3
      resources:
        requests:
          cpu: "2"
          memory: 5Gi
        limits:
          cpu: "20"
          memory: 20Gi

istio:

  global:
    imagePullPolicy: IfNotPresent

  sidecarInjectorWebhook:
    rewriteAppHTTPProbe: true

  galley:
    enabled: false

  gateways:
    istio-ingressgateway:
      enabled: false  # This is disabled here to work around limitation of istio 1.5. It's enabled in the cray-istio chart.
      type: LoadBalancer
      autoscaleEnabled: true
      autoscaleMin: 2
      autoscaleMax: 5
      ports:
      - port: 80
        name: http2
      - port: 443
        name: https
      env:
        ISTIO_META_IDLE_TIMEOUT: 10m

  prometheus:
    retention: 4h
    security:
      enabled: false

  grafana:
    security:
      enabled: false

  tracing:
    enabled: true
    provider: jaeger
    jaeger:
      memory:
        max_traces: 50000

  kiali:
    dashboard:
      auth:
        strategy: anonymous
      grafanaURL: https://grafana-istio.local/
      jaegerURL: https://jaeger-istio.local/
# cray-istio has been setting custom_metrics_url per the kiali documentation
# https://kiali.io/documentation/runtimes-monitoring/#_prometheus_configuration
# but the istio/kiali chart sets url. This value also adds the custom_metrics_url
# setting at the right indentation in the generated kiali ConfigMap. Maybe this
# workaround can be removed in a future release.
    prometheusAddr: |
      http://prometheus.istio-system:9090
              custom_metrics_url: http://prometheus.istio-system:9090/
    createDemoSecret: false

  pilot:
    env:
      USE_ISTIO_JWT_FILTER: "true"
      PILOT_ENABLE_UNSAFE_REGEX: "true"
