apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: cray-dmtf-resource-event
  labels:
    strimzi.io/cluster: {{ template "cray-shared-kafka.name" . }}
    app: {{ template "cray-shared-kafka.name" . }}
{{ include "cray-shared-kafka.labels" . | indent 4 }}
spec:
  partitions: 4
  replicas: 2
  config:
    retention.ms: 14400000
    segment.bytes: 1048576
